/// Flutter icons FoodistaanCustomIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FoodistaanCustomIcon
///      fonts:
///       - asset: fonts/FoodistaanCustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FoodistaanCustomIcon {
  FoodistaanCustomIcon._();

  static const _kFontFam = 'FoodistaanCustomIcon';
  static const String? _kFontPkg = null;

  static const IconData group__1_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group__2_ = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group__3_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
